name: Server Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  server-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Server - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'
          java-package: jdk
      - name: Server - Run Unit Tests
        working-directory: ./server
        run: ./gradlew test
      - name: Server - Run Lint Check
        working-directory: ./server
        run: ./gradlew spotlessCheck
